server.port=8080
spring.application.name=educationweb
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.thymeleaf.cache=false

oauth2.client.id=education-client
oauth2.client.secret=education-secret
